.TH "Cuts" 3 "Fri Jan 30 2015" "RPV-LFV-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cuts \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CutClass\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCuts\fP ()"
.br
.ti -1c
.RI "\fBCuts\fP (const std::string name)"
.br
.ti -1c
.RI "\fBCuts\fP (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max)"
.br
.ti -1c
.RI "\fBCuts\fP (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, std::string i_x_title)"
.br
.ti -1c
.RI "\fBCuts\fP (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, int i_n_bins_y, double i_y_min, double i_y_max)"
.br
.ti -1c
.RI "\fBCuts\fP (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, int i_n_bins_y, double i_y_min, double i_y_max, std::string i_x_title, std::string i_y_title)"
.br
.ti -1c
.RI "\fBCuts\fP (const \fBCuts\fP &a)"
.br
.ti -1c
.RI "\fB~Cuts\fP ()"
.br
.ti -1c
.RI "void \fBSetPassed\fP (bool passed)"
.br
.ti -1c
.RI "void \fBSetVars\fP (double i_var_1)"
.br
.ti -1c
.RI "void \fBSetVars\fP (double i_var_1, double i_var_2)"
.br
.ti -1c
.RI "int \fBdim\fP ()"
.br
.ti -1c
.RI "int \fBbx\fP ()"
.br
.ti -1c
.RI "int \fBby\fP ()"
.br
.ti -1c
.RI "double \fBxmi\fP ()"
.br
.ti -1c
.RI "double \fBxma\fP ()"
.br
.ti -1c
.RI "double \fBymi\fP ()"
.br
.ti -1c
.RI "double \fByma\fP ()"
.br
.ti -1c
.RI "double \fBv1\fP ()"
.br
.ti -1c
.RI "double \fBv2\fP ()"
.br
.ti -1c
.RI "bool \fBpass\fP ()"
.br
.ti -1c
.RI "std::string \fBxt\fP ()"
.br
.ti -1c
.RI "std::string \fByt\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBcut_name\fP"
.br
.ti -1c
.RI "bool \fBcut_passed\fP"
.br
.ti -1c
.RI "int \fBdimensions\fP"
.br
.ti -1c
.RI "int \fBn_bins_x\fP"
.br
.ti -1c
.RI "double \fBx_min\fP"
.br
.ti -1c
.RI "double \fBx_max\fP"
.br
.ti -1c
.RI "int \fBn_bins_y\fP"
.br
.ti -1c
.RI "double \fBy_min\fP"
.br
.ti -1c
.RI "double \fBy_max\fP"
.br
.ti -1c
.RI "double \fBvar_1\fP"
.br
.ti -1c
.RI "double \fBvar_2\fP"
.br
.ti -1c
.RI "std::string \fBx_title\fP"
.br
.ti -1c
.RI "std::string \fBy_title\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file CutClass\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Cuts::Cuts ()\fC [inline]\fP"

.PP
Definition at line 7 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const std::stringname)\fC [inline]\fP"

.PP
Definition at line 22 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const std::stringname, inti_n_bins_x, doublei_x_min, doublei_x_max)\fC [inline]\fP"

.PP
Definition at line 37 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const std::stringname, inti_n_bins_x, doublei_x_min, doublei_x_max, std::stringi_x_title)\fC [inline]\fP"

.PP
Definition at line 52 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const std::stringname, inti_n_bins_x, doublei_x_min, doublei_x_max, inti_n_bins_y, doublei_y_min, doublei_y_max)\fC [inline]\fP"

.PP
Definition at line 67 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const std::stringname, inti_n_bins_x, doublei_x_min, doublei_x_max, inti_n_bins_y, doublei_y_min, doublei_y_max, std::stringi_x_title, std::stringi_y_title)\fC [inline]\fP"

.PP
Definition at line 82 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const \fBCuts\fP &a)\fC [inline]\fP"

.PP
Definition at line 97 of file CutClass\&.hh\&.
.SS "Cuts::~Cuts ()\fC [inline]\fP"

.PP
Definition at line 99 of file CutClass\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "int Cuts::bx ()\fC [inline]\fP"

.PP
Definition at line 118 of file CutClass\&.hh\&.
.PP
References n_bins_x\&.
.SS "int Cuts::by ()\fC [inline]\fP"

.PP
Definition at line 122 of file CutClass\&.hh\&.
.PP
References n_bins_y\&.
.SS "int Cuts::dim ()\fC [inline]\fP"

.PP
Definition at line 114 of file CutClass\&.hh\&.
.PP
References dimensions\&.
.SS "bool Cuts::pass ()\fC [inline]\fP"

.PP
Definition at line 150 of file CutClass\&.hh\&.
.PP
References cut_passed\&.
.SS "void Cuts::SetPassed (boolpassed)\fC [inline]\fP"

.PP
Definition at line 101 of file CutClass\&.hh\&.
.PP
References cut_passed\&.
.SS "void Cuts::SetVars (doublei_var_1)\fC [inline]\fP"

.PP
Definition at line 105 of file CutClass\&.hh\&.
.PP
References var_1\&.
.PP
Referenced by specialAna::Bjet_veto(), specialAna::Leptonic_fraction_cut(), specialAna::Make_DeltaPhi_emu(), specialAna::Make_DeltaPhi_mutau(), specialAna::Make_DeltaPhi_tauemu(), specialAna::Make_DeltaPhi_tauMET(), specialAna::Make_zeta_cut(), specialAna::MT_cut(), specialAna::OppSign_charge(), specialAna::pT_muele_ratio_cut(), and specialAna::pT_mutau_ratio_cut()\&.
.SS "void Cuts::SetVars (doublei_var_1, doublei_var_2)\fC [inline]\fP"

.PP
Definition at line 109 of file CutClass\&.hh\&.
.PP
References var_1, and var_2\&.
.SS "double Cuts::v1 ()\fC [inline]\fP"

.PP
Definition at line 142 of file CutClass\&.hh\&.
.PP
References var_1\&.
.SS "double Cuts::v2 ()\fC [inline]\fP"

.PP
Definition at line 146 of file CutClass\&.hh\&.
.PP
References var_2\&.
.SS "double Cuts::xma ()\fC [inline]\fP"

.PP
Definition at line 130 of file CutClass\&.hh\&.
.PP
References x_max\&.
.SS "double Cuts::xmi ()\fC [inline]\fP"

.PP
Definition at line 126 of file CutClass\&.hh\&.
.PP
References x_min\&.
.SS "std::string Cuts::xt ()\fC [inline]\fP"

.PP
Definition at line 154 of file CutClass\&.hh\&.
.PP
References x_title\&.
.SS "double Cuts::yma ()\fC [inline]\fP"

.PP
Definition at line 138 of file CutClass\&.hh\&.
.PP
References y_max\&.
.SS "double Cuts::ymi ()\fC [inline]\fP"

.PP
Definition at line 134 of file CutClass\&.hh\&.
.PP
References y_min\&.
.SS "std::string Cuts::yt ()\fC [inline]\fP"

.PP
Definition at line 158 of file CutClass\&.hh\&.
.PP
References y_title\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string Cuts::cut_name\fC [private]\fP"

.PP
Definition at line 164 of file CutClass\&.hh\&.
.SS "bool Cuts::cut_passed\fC [private]\fP"

.PP
Definition at line 165 of file CutClass\&.hh\&.
.PP
Referenced by pass(), and SetPassed()\&.
.SS "int Cuts::dimensions\fC [private]\fP"

.PP
Definition at line 166 of file CutClass\&.hh\&.
.PP
Referenced by dim()\&.
.SS "int Cuts::n_bins_x\fC [private]\fP"

.PP
Definition at line 167 of file CutClass\&.hh\&.
.PP
Referenced by bx()\&.
.SS "int Cuts::n_bins_y\fC [private]\fP"

.PP
Definition at line 170 of file CutClass\&.hh\&.
.PP
Referenced by by()\&.
.SS "double Cuts::var_1\fC [private]\fP"

.PP
Definition at line 173 of file CutClass\&.hh\&.
.PP
Referenced by SetVars(), and v1()\&.
.SS "double Cuts::var_2\fC [private]\fP"

.PP
Definition at line 174 of file CutClass\&.hh\&.
.PP
Referenced by SetVars(), and v2()\&.
.SS "double Cuts::x_max\fC [private]\fP"

.PP
Definition at line 169 of file CutClass\&.hh\&.
.PP
Referenced by xma()\&.
.SS "double Cuts::x_min\fC [private]\fP"

.PP
Definition at line 168 of file CutClass\&.hh\&.
.PP
Referenced by xmi()\&.
.SS "std::string Cuts::x_title\fC [private]\fP"

.PP
Definition at line 175 of file CutClass\&.hh\&.
.PP
Referenced by xt()\&.
.SS "double Cuts::y_max\fC [private]\fP"

.PP
Definition at line 172 of file CutClass\&.hh\&.
.PP
Referenced by yma()\&.
.SS "double Cuts::y_min\fC [private]\fP"

.PP
Definition at line 171 of file CutClass\&.hh\&.
.PP
Referenced by ymi()\&.
.SS "std::string Cuts::y_title\fC [private]\fP"

.PP
Definition at line 176 of file CutClass\&.hh\&.
.PP
Referenced by yt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RPV-LFV-Analyzer from the source code\&.
