RPV-LFV-Analyzer: Trigger Class Reference
Trigger Class Reference
#include <TriggerClass.hh>
Public Member Functions
Trigger (std::string input_trigger_name)
void DoAcceptCuts (bool accep_cuts=true)
bool GetDimension () const
bool GetAcceptCuts () const
std::string GetPart1Name () const
std::string GetPart2Name () const
Private Member Functions
void split (const std::string &s, char delim, std::vector< std::string > *elems)
std::vector< std::string > split (const std::string &s, char delim)
std::vector< std::string > Get_trigger_seeds (const std::string input_trigger_name)
Private Attributes
std::string trigger_name
std::string part_1_name
std::string part_2_name
bool two_dimensions
bool do_accept_cuts
std::vector< pxl::Particle * > * particles_1
std::vector< pxl::Particle * > * particles_2
Detailed Description
Definition at line 7 of file TriggerClass.hh.
Constructor & Destructor Documentation
Trigger::Trigger (std::string input_trigger_name) inline explicit
Definition at line 9 of file TriggerClass.hh.
References Get_trigger_seeds(), part_1_name, part_2_name, trigger_name, and two_dimensions.
Member Function Documentation
void Trigger::DoAcceptCuts (bool accep_cuts = true) inline
Definition at line 17 of file TriggerClass.hh.
References do_accept_cuts.
std::vector< std::string > Trigger::Get_trigger_seeds (const std::string input_trigger_name) inline private
Definition at line 52 of file TriggerClass.hh.
References part_1_name, part_2_name, split(), and two_dimensions.
Referenced by Trigger().
bool Trigger::GetAcceptCuts () const inline
Definition at line 25 of file TriggerClass.hh.
References do_accept_cuts.
bool Trigger::GetDimension () const inline
Definition at line 21 of file TriggerClass.hh.
References two_dimensions.
std::string Trigger::GetPart1Name () const inline
Definition at line 29 of file TriggerClass.hh.
References part_1_name.
std::string Trigger::GetPart2Name () const inline
Definition at line 33 of file TriggerClass.hh.
References part_2_name.
void Trigger::split (const std::string & s, char delim, std::vector< std::string > * elems) inline private
Definition at line 38 of file TriggerClass.hh.
Referenced by Get_trigger_seeds(), and split().
std::vector<std::string> Trigger::split (const std::string & s, char delim) inline private
Definition at line 46 of file TriggerClass.hh.
References split().
Member Data Documentation
bool Trigger::do_accept_cuts private
Definition at line 97 of file TriggerClass.hh.
Referenced by DoAcceptCuts(), and GetAcceptCuts().
std::string Trigger::part_1_name private
Definition at line 94 of file TriggerClass.hh.
Referenced by Get_trigger_seeds(), GetPart1Name(), and Trigger().
std::string Trigger::part_2_name private
Definition at line 95 of file TriggerClass.hh.
Referenced by Get_trigger_seeds(), GetPart2Name(), and Trigger().
std::vector< pxl::Particle* >* Trigger::particles_1 private
Definition at line 98 of file TriggerClass.hh.
std::vector< pxl::Particle* >* Trigger::particles_2 private
Definition at line 99 of file TriggerClass.hh.
std::string Trigger::trigger_name private
Definition at line 93 of file TriggerClass.hh.
Referenced by Trigger().
bool Trigger::two_dimensions private
Definition at line 96 of file TriggerClass.hh.
Referenced by Get_trigger_seeds(), GetDimension(), and Trigger().
The documentation for this class was generated from the following file:
TriggerClass.hh