RPV-LFV-Analyzer: Cuts Class Reference
Cuts Class Reference
#include <CutClass.hh>
Public Member Functions
Cuts ()
Cuts (const std::string name)
Cuts (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max)
Cuts (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, std::string i_x_title)
Cuts (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, int i_n_bins_y, double i_y_min, double i_y_max)
Cuts (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, int i_n_bins_y, double i_y_min, double i_y_max, std::string i_x_title, std::string i_y_title)
Cuts (const Cuts &a)
~Cuts ()
void SetPassed (bool passed)
void SetVars (double i_var_1)
void SetVars (double i_var_1, double i_var_2)
int dim () const
int bx () const
int by () const
double xmi () const
double xma () const
double ymi () const
double yma () const
double v1 () const
double v2 () const
bool pass () const
std::string xt () const
std::string yt () const
Private Attributes
std::string cut_name
bool cut_passed
int dimensions
int n_bins_x
double x_min
double x_max
int n_bins_y
double y_min
double y_max
double var_1
double var_2
std::string x_title
std::string y_title
Detailed Description
Definition at line 6 of file CutClass.hh.
Constructor & Destructor Documentation
Cuts::Cuts () inline
Definition at line 8 of file CutClass.hh.
Cuts::Cuts (const std::string name) inline explicit
Definition at line 24 of file CutClass.hh.
Cuts::Cuts (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max) inline
Definition at line 40 of file CutClass.hh.
Cuts::Cuts (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, std::string i_x_title) inline
Definition at line 56 of file CutClass.hh.
Cuts::Cuts (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, int i_n_bins_y, double i_y_min, double i_y_max) inline
Definition at line 72 of file CutClass.hh.
Cuts::Cuts (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, int i_n_bins_y, double i_y_min, double i_y_max, std::string i_x_title, std::string i_y_title) inline
Definition at line 88 of file CutClass.hh.
Cuts::Cuts (const Cuts & a) inline
Definition at line 104 of file CutClass.hh.
Cuts::~Cuts () inline
Definition at line 107 of file CutClass.hh.
Member Function Documentation
int Cuts::bx () const inline
Definition at line 127 of file CutClass.hh.
References n_bins_x.
int Cuts::by () const inline
Definition at line 131 of file CutClass.hh.
References n_bins_y.
int Cuts::dim () const inline
Definition at line 123 of file CutClass.hh.
References dimensions.
bool Cuts::pass () const inline
Definition at line 159 of file CutClass.hh.
References cut_passed.
void Cuts::SetPassed (bool passed) inline
Definition at line 110 of file CutClass.hh.
References cut_passed.
void Cuts::SetVars (double i_var_1) inline
Definition at line 114 of file CutClass.hh.
References var_1.
Referenced by specialAna::Bjet_veto(), specialAna::Leptonic_fraction_cut(), specialAna::Make_DeltaPhi_emu(), specialAna::Make_DeltaPhi_mutau(), specialAna::Make_DeltaPhi_tauemu(), specialAna::Make_DeltaPhi_tauMET(), specialAna::Make_zeta_cut(), specialAna::MT_cut(), specialAna::OppSign_charge(), specialAna::pT_muele_ratio_cut(), and specialAna::pT_mutau_ratio_cut().
void Cuts::SetVars (double i_var_1, double i_var_2) inline
Definition at line 118 of file CutClass.hh.
References var_1, and var_2.
double Cuts::v1 () const inline
Definition at line 151 of file CutClass.hh.
References var_1.
double Cuts::v2 () const inline
Definition at line 155 of file CutClass.hh.
References var_2.
double Cuts::xma () const inline
Definition at line 139 of file CutClass.hh.
References x_max.
double Cuts::xmi () const inline
Definition at line 135 of file CutClass.hh.
References x_min.
std::string Cuts::xt () const inline
Definition at line 163 of file CutClass.hh.
References x_title.
double Cuts::yma () const inline
Definition at line 147 of file CutClass.hh.
References y_max.
double Cuts::ymi () const inline
Definition at line 143 of file CutClass.hh.
References y_min.
std::string Cuts::yt () const inline
Definition at line 167 of file CutClass.hh.
References y_title.
Member Data Documentation
std::string Cuts::cut_name private
Definition at line 172 of file CutClass.hh.
bool Cuts::cut_passed private
Definition at line 173 of file CutClass.hh.
Referenced by pass(), and SetPassed().
int Cuts::dimensions private
Definition at line 174 of file CutClass.hh.
Referenced by dim().
int Cuts::n_bins_x private
Definition at line 175 of file CutClass.hh.
Referenced by bx().
int Cuts::n_bins_y private
Definition at line 178 of file CutClass.hh.
Referenced by by().
double Cuts::var_1 private
Definition at line 181 of file CutClass.hh.
Referenced by SetVars(), and v1().
double Cuts::var_2 private
Definition at line 182 of file CutClass.hh.
Referenced by SetVars(), and v2().
double Cuts::x_max private
Definition at line 177 of file CutClass.hh.
Referenced by xma().
double Cuts::x_min private
Definition at line 176 of file CutClass.hh.
Referenced by xmi().
std::string Cuts::x_title private
Definition at line 183 of file CutClass.hh.
Referenced by xt().
double Cuts::y_max private
Definition at line 180 of file CutClass.hh.
Referenced by yma().
double Cuts::y_min private
Definition at line 179 of file CutClass.hh.
Referenced by ymi().
std::string Cuts::y_title private
Definition at line 184 of file CutClass.hh.
Referenced by yt().
The documentation for this class was generated from the following file:
CutClass.hh