RPV-LFV-Analyzer: specialAna.cc File Reference
specialAna.cc File Reference
#include "specialAna.hh"
#include "HistClass.hh"
#include "Tools/Tools.hh"
#include "boost/format.hpp"
Functions
m_dataPeriod (cfg.GetItem< string >("General.DataPeriod"))
m_channel (cfg.GetItem< string >("RPV.channel"))
config_ (cfg)
Function Documentation
config_ (cfg)
Init for the e-mu channel
Init for the e-tau_h channel
Init for the mu-tau_h channel
Init for the e-tau_e channel
Init for the e-tau_mu channel
Init for the mu-tau_e channel
Init for the mu-tau_mu channel
Definition at line 21 of file specialAna.cc.
References m_channel(), and m_dataPeriod().
m_channel (cfg.GetItem< string > "RPV.channel")
Referenced by config_().
m_dataPeriod (cfg.GetItem< string > "General.DataPeriod")
Referenced by config_().