.TH "Cuts" 3 "Thu Feb 12 2015" "RPV-LFV-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cuts \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CutClass\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCuts\fP ()"
.br
.ti -1c
.RI "\fBCuts\fP (const std::string name)"
.br
.ti -1c
.RI "\fBCuts\fP (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max)"
.br
.ti -1c
.RI "\fBCuts\fP (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, std::string i_x_title)"
.br
.ti -1c
.RI "\fBCuts\fP (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, int i_n_bins_y, double i_y_min, double i_y_max)"
.br
.ti -1c
.RI "\fBCuts\fP (const std::string name, int i_n_bins_x, double i_x_min, double i_x_max, int i_n_bins_y, double i_y_min, double i_y_max, std::string i_x_title, std::string i_y_title)"
.br
.ti -1c
.RI "\fBCuts\fP (const \fBCuts\fP &a)"
.br
.ti -1c
.RI "\fB~Cuts\fP ()"
.br
.ti -1c
.RI "void \fBSetPassed\fP (bool passed)"
.br
.ti -1c
.RI "void \fBSetVars\fP (double i_var_1)"
.br
.ti -1c
.RI "void \fBSetVars\fP (double i_var_1, double i_var_2)"
.br
.ti -1c
.RI "int \fBdim\fP () const "
.br
.ti -1c
.RI "int \fBbx\fP () const "
.br
.ti -1c
.RI "int \fBby\fP () const "
.br
.ti -1c
.RI "double \fBxmi\fP () const "
.br
.ti -1c
.RI "double \fBxma\fP () const "
.br
.ti -1c
.RI "double \fBymi\fP () const "
.br
.ti -1c
.RI "double \fByma\fP () const "
.br
.ti -1c
.RI "double \fBv1\fP () const "
.br
.ti -1c
.RI "double \fBv2\fP () const "
.br
.ti -1c
.RI "bool \fBpass\fP () const "
.br
.ti -1c
.RI "std::string \fBxt\fP () const "
.br
.ti -1c
.RI "std::string \fByt\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBcut_name\fP"
.br
.ti -1c
.RI "bool \fBcut_passed\fP"
.br
.ti -1c
.RI "int \fBdimensions\fP"
.br
.ti -1c
.RI "int \fBn_bins_x\fP"
.br
.ti -1c
.RI "double \fBx_min\fP"
.br
.ti -1c
.RI "double \fBx_max\fP"
.br
.ti -1c
.RI "int \fBn_bins_y\fP"
.br
.ti -1c
.RI "double \fBy_min\fP"
.br
.ti -1c
.RI "double \fBy_max\fP"
.br
.ti -1c
.RI "double \fBvar_1\fP"
.br
.ti -1c
.RI "double \fBvar_2\fP"
.br
.ti -1c
.RI "std::string \fBx_title\fP"
.br
.ti -1c
.RI "std::string \fBy_title\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file CutClass\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Cuts::Cuts ()\fC [inline]\fP"

.PP
Definition at line 8 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const std::stringname)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 24 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const std::stringname, inti_n_bins_x, doublei_x_min, doublei_x_max)\fC [inline]\fP"

.PP
Definition at line 40 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const std::stringname, inti_n_bins_x, doublei_x_min, doublei_x_max, std::stringi_x_title)\fC [inline]\fP"

.PP
Definition at line 56 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const std::stringname, inti_n_bins_x, doublei_x_min, doublei_x_max, inti_n_bins_y, doublei_y_min, doublei_y_max)\fC [inline]\fP"

.PP
Definition at line 72 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const std::stringname, inti_n_bins_x, doublei_x_min, doublei_x_max, inti_n_bins_y, doublei_y_min, doublei_y_max, std::stringi_x_title, std::stringi_y_title)\fC [inline]\fP"

.PP
Definition at line 88 of file CutClass\&.hh\&.
.SS "Cuts::Cuts (const \fBCuts\fP &a)\fC [inline]\fP"

.PP
Definition at line 104 of file CutClass\&.hh\&.
.SS "Cuts::~Cuts ()\fC [inline]\fP"

.PP
Definition at line 107 of file CutClass\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "int Cuts::bx () const\fC [inline]\fP"

.PP
Definition at line 127 of file CutClass\&.hh\&.
.PP
References n_bins_x\&.
.SS "int Cuts::by () const\fC [inline]\fP"

.PP
Definition at line 131 of file CutClass\&.hh\&.
.PP
References n_bins_y\&.
.SS "int Cuts::dim () const\fC [inline]\fP"

.PP
Definition at line 123 of file CutClass\&.hh\&.
.PP
References dimensions\&.
.SS "bool Cuts::pass () const\fC [inline]\fP"

.PP
Definition at line 159 of file CutClass\&.hh\&.
.PP
References cut_passed\&.
.SS "void Cuts::SetPassed (boolpassed)\fC [inline]\fP"

.PP
Definition at line 110 of file CutClass\&.hh\&.
.PP
References cut_passed\&.
.SS "void Cuts::SetVars (doublei_var_1)\fC [inline]\fP"

.PP
Definition at line 114 of file CutClass\&.hh\&.
.PP
References var_1\&.
.PP
Referenced by specialAna::Bjet_veto(), specialAna::Leptonic_fraction_cut(), specialAna::Make_DeltaPhi_emu(), specialAna::Make_DeltaPhi_mutau(), specialAna::Make_DeltaPhi_tauemu(), specialAna::Make_DeltaPhi_tauMET(), specialAna::Make_zeta_cut(), specialAna::MT_cut(), specialAna::OppSign_charge(), specialAna::pT_muele_ratio_cut(), and specialAna::pT_mutau_ratio_cut()\&.
.SS "void Cuts::SetVars (doublei_var_1, doublei_var_2)\fC [inline]\fP"

.PP
Definition at line 118 of file CutClass\&.hh\&.
.PP
References var_1, and var_2\&.
.SS "double Cuts::v1 () const\fC [inline]\fP"

.PP
Definition at line 151 of file CutClass\&.hh\&.
.PP
References var_1\&.
.SS "double Cuts::v2 () const\fC [inline]\fP"

.PP
Definition at line 155 of file CutClass\&.hh\&.
.PP
References var_2\&.
.SS "double Cuts::xma () const\fC [inline]\fP"

.PP
Definition at line 139 of file CutClass\&.hh\&.
.PP
References x_max\&.
.SS "double Cuts::xmi () const\fC [inline]\fP"

.PP
Definition at line 135 of file CutClass\&.hh\&.
.PP
References x_min\&.
.SS "std::string Cuts::xt () const\fC [inline]\fP"

.PP
Definition at line 163 of file CutClass\&.hh\&.
.PP
References x_title\&.
.SS "double Cuts::yma () const\fC [inline]\fP"

.PP
Definition at line 147 of file CutClass\&.hh\&.
.PP
References y_max\&.
.SS "double Cuts::ymi () const\fC [inline]\fP"

.PP
Definition at line 143 of file CutClass\&.hh\&.
.PP
References y_min\&.
.SS "std::string Cuts::yt () const\fC [inline]\fP"

.PP
Definition at line 167 of file CutClass\&.hh\&.
.PP
References y_title\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string Cuts::cut_name\fC [private]\fP"

.PP
Definition at line 172 of file CutClass\&.hh\&.
.SS "bool Cuts::cut_passed\fC [private]\fP"

.PP
Definition at line 173 of file CutClass\&.hh\&.
.PP
Referenced by pass(), and SetPassed()\&.
.SS "int Cuts::dimensions\fC [private]\fP"

.PP
Definition at line 174 of file CutClass\&.hh\&.
.PP
Referenced by dim()\&.
.SS "int Cuts::n_bins_x\fC [private]\fP"

.PP
Definition at line 175 of file CutClass\&.hh\&.
.PP
Referenced by bx()\&.
.SS "int Cuts::n_bins_y\fC [private]\fP"

.PP
Definition at line 178 of file CutClass\&.hh\&.
.PP
Referenced by by()\&.
.SS "double Cuts::var_1\fC [private]\fP"

.PP
Definition at line 181 of file CutClass\&.hh\&.
.PP
Referenced by SetVars(), and v1()\&.
.SS "double Cuts::var_2\fC [private]\fP"

.PP
Definition at line 182 of file CutClass\&.hh\&.
.PP
Referenced by SetVars(), and v2()\&.
.SS "double Cuts::x_max\fC [private]\fP"

.PP
Definition at line 177 of file CutClass\&.hh\&.
.PP
Referenced by xma()\&.
.SS "double Cuts::x_min\fC [private]\fP"

.PP
Definition at line 176 of file CutClass\&.hh\&.
.PP
Referenced by xmi()\&.
.SS "std::string Cuts::x_title\fC [private]\fP"

.PP
Definition at line 183 of file CutClass\&.hh\&.
.PP
Referenced by xt()\&.
.SS "double Cuts::y_max\fC [private]\fP"

.PP
Definition at line 180 of file CutClass\&.hh\&.
.PP
Referenced by yma()\&.
.SS "double Cuts::y_min\fC [private]\fP"

.PP
Definition at line 179 of file CutClass\&.hh\&.
.PP
Referenced by ymi()\&.
.SS "std::string Cuts::y_title\fC [private]\fP"

.PP
Definition at line 184 of file CutClass\&.hh\&.
.PP
Referenced by yt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RPV-LFV-Analyzer from the source code\&.
