.TH "specialAna.cc" 3 "Wed Feb 4 2015" "RPV-LFV-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
specialAna.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'specialAna\&.hh'\fP
.br
\fC#include 'HistClass\&.hh'\fP
.br
\fC#include 'Tools/Tools\&.hh'\fP
.br
\fC#include 'boost/format\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBm_dataPeriod\fP (cfg\&.GetItem< std::string >('General\&.DataPeriod'))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "m_dataPeriod (cfg\&.GetItem< std::string >'General\&.DataPeriod')"

.SH "Author"
.PP 
Generated automatically by Doxygen for RPV-LFV-Analyzer from the source code\&.
