RPV-LFV-Analyzer: specialAna Class Reference
specialAna Class Reference
clean up the header!!!
#include <specialAna.hh>
Public Member Functions
specialAna (const Tools::MConfig &config)
virtual ~specialAna ()
virtual void endJob (const Serializable *)
virtual void analyseEvent (const pxl::Event *event)
void channel_writer (TFile *file, const char *channel)
bool tail_selector (const pxl::Event *event)
void Create_Gen_histograms (const char *channel, const char *part1, const char *part2)
void Fill_Gen_histograms (const char *channel, const char *part1, const char *part2)
void Init_emu_cuts ()
void Init_etau_cuts ()
void Init_mutau_cuts ()
void Init_etaue_cuts ()
void Init_etaumu_cuts ()
void Init_mutaue_cuts ()
void Init_mutaumu_cuts ()
void FillControllHistos ()
void Create_trigger_effs ()
void Fill_trigger_effs ()
void Create_N1_histos (const char *channel, const std::map< std::string, Cuts > &m_cfg, std::string const endung="")
void Fill_N1_histos (const char *channel, const std::map< std::string, Cuts > &m_cfg, std::string const endung="")
void Create_Resonance_histograms (int n_histos, const char *channel, const char *part1, const char *part2, std::string const endung="")
void Fill_Resonance_histograms (int n_histos, const char *channel, const char *part1, const char *part2, std::string const endung="")
void KinematicsSelector (std::string const endung="")
bool FindResonance (const char *channel, std::vector< pxl::Particle * > gen_list)
bool FindResonance (const char *channel, std::vector< pxl::Particle * > part1_list, std::vector< pxl::Particle * > part2_list)
bool FindResonance (const char *channel, std::vector< pxl::Particle * > part1_list, std::vector< pxl::Particle * > part2_list, std::vector< pxl::Particle * > met_list)
void GenSelector ()
void Fill_Gen_Controll_histo ()
void Fill_Particle_histos (int hist_number, pxl::Particle *lepton)
void Fill_Gen_histograms (int n_histos, const char *channel, const char *part1, const char *part2)
void Get_Trigger_match_1 (std::string trigger_name)
void Get_Trigger_match_2 (std::string trigger_name)
pxl::Particle * Get_Truth_match (std::string name, pxl::Particle *lepton)
void Create_RECO_effs ()
void Create_RECO_object_effs (std::string object)
void Fill_RECO_effs ()
void Fill_RECO_object_effs (std::string object, int id, std::vector< pxl::Particle * > part_list)
void FillSystematics (const pxl::Event *event, std::string const particleName)
void FillSystematicsUpDown (const pxl::Event *event, std::string const particleName, std::string const updown, std::string const shiftType)
void initEvent (const pxl::Event *event)
void endEvent (const pxl::Event *event)
bool Check_Par_ID (pxl::Particle *part, bool do_pt_cut=true, bool do_eta_cut=true)
bool Check_Muo_ID (pxl::Particle *muon, bool do_pt_cut=true, bool do_eta_cut=true)
bool Check_Tau_ID (pxl::Particle *tau)
bool Check_Ele_ID (pxl::Particle *ele, bool do_pt_cut=true, bool do_eta_cut=true)
std::vector< double > Make_zeta_stuff (pxl::Particle *muon, pxl::Particle *tau, pxl::Particle *met)
bool Make_zeta_cut (Cuts *cuts)
bool Make_DeltaPhi_tauMET (Cuts *cuts)
bool Make_DeltaPhi_mutau (Cuts *cuts)
bool Make_DeltaPhi_tauemu (Cuts *cuts)
bool Bjet_veto (Cuts *cuts)
bool OppSign_charge (Cuts *cuts)
bool MT_cut (Cuts *cuts)
double calc_lep_fraction ()
bool Leptonic_fraction_cut (Cuts *cuts)
bool pT_mutau_ratio_cut (Cuts *cuts)
bool pT_muele_ratio_cut (Cuts *cuts)
bool Make_DeltaPhi_emu (Cuts *cuts)
bool TriggerSelector (const pxl::Event *event)
double DeltaPhi (double a, double b)
double DeltaPhi (pxl::Particle *lepton, pxl::Particle *met)
double DeltaR (pxl::Particle *lepton, pxl::Particle *met)
double MT (pxl::Particle *lepton, pxl::Particle *met)
double getPtHat ()
double getHT ()
Public Attributes
TFile * file1
pxl::EventView * m_RecEvtView
pxl::EventView * m_GenEvtView
pxl::EventView * m_TrigEvtView
bool runOnData
bool doTriggerStudies
const std::string m_JetAlgo
const std::string m_BJets_algo
const std::string m_METType
const std::string m_TauType
const std::string particles [4] = {"Ele", "Muon", "Tau", "MET"}
const std::string particleSymbols [4] = {"e", "#mu", "#tau", "E_{T}^{miss}"}
TString d_mydisc [66]
bool isOldPXLFile
const std::string m_cutdatafile
const std::vector< std::string > m_trigger_string
TString d_mydiscmu [6]
const std::string m_dataPeriod
const std::string m_channel
const Tools::MConfig config_
double temp_run
double temp_ls
double temp_event
double weight
unsigned int numMuon
unsigned int numEle
unsigned int numTau
unsigned int numGamma
unsigned int numMET
unsigned int numJet
unsigned int numBJet
int events_
unsigned int n_lepton
std::vector< pxl::Particle * > * EleList
std::vector< pxl::Particle * > * MuonList
std::vector< pxl::Particle * > * TauList
std::vector< pxl::Particle * > * GammaList
std::vector< pxl::Particle * > * METList
std::vector< pxl::Particle * > * JetList
std::vector< pxl::Particle * > * BJetList
std::vector< pxl::Particle * > * RememberPart
std::vector< pxl::Particle * > * RememberMET
std::vector< pxl::Particle * > * EleListGen
std::vector< pxl::Particle * > * MuonListGen
std::vector< pxl::Particle * > * TauListGen
std::vector< pxl::Particle * > * GammaListGen
std::vector< pxl::Particle * > * METListGen
std::vector< pxl::Particle * > * JetListGen
std::vector< pxl::Particle * > * S3ListGen
bool b_14TeV
bool b_13TeV
bool b_8TeV
bool b_emu
bool b_etau
bool b_mutau
bool b_etaue
bool b_etaumu
bool b_mutaue
bool b_mutaumu
std::map< std::string, Cuts > emu_cut_cfgs
std::map< std::string, Cuts > etau_cut_cfgs
std::map< std::string, Cuts > mutau_cut_cfgs
std::map< std::string, Cuts > etaue_cut_cfgs
std::map< std::string, Cuts > etaumu_cut_cfgs
std::map< std::string, Cuts > mutaue_cut_cfgs
std::map< std::string, Cuts > mutaumu_cut_cfgs
std::map< std::string, Trigger * > trigger_defs
std::map< std::string, int > channel_stages
pxl::Particle * sel_part1_gen
pxl::Particle * sel_part2_gen
pxl::Particle * sel_lepton_prompt
pxl::Particle * sel_lepton_nprompt
pxl::Particle * sel_met
pxl::Particle * sel_lepton_nprompt_corr
std::map< std::string, double > resonance_mass
std::map< std::string, double > resonance_mass_gen
std::unordered_set< std::string > triggers
std::map< std::string, float > mLeptonTree
bool keep_data_event
std::map< std::string, float > mkeep_resonance_mass
double event_weight
double pileup_weight
Detailed Description
clean up the header!!!
Definition at line 28 of file specialAna.hh.
Constructor & Destructor Documentation
specialAna::specialAna (const Tools::MConfig & config) explicit
Definition at line 10 of file specialAna.cc.
specialAna::~specialAna () virtual
Definition at line 290 of file specialAna.cc.
Member Function Documentation
void specialAna::analyseEvent (const pxl::Event * event) virtual
Definition at line 293 of file specialAna.cc.
References Check_Muo_ID(), Check_Tau_ID(), doTriggerStudies, EleList, endEvent(), Fill_Gen_Controll_histo(), Fill_Particle_histos(), Fill_RECO_effs(), Fill_trigger_effs(), FillControllHistos(), FillSystematics(), FillSystematicsUpDown(), GenSelector(), initEvent(), KinematicsSelector(), METList, MuonList, runOnData, tail_selector(), TauList, TriggerSelector(), and weight.
bool specialAna::Bjet_veto (Cuts * cuts)
Definition at line 1716 of file specialAna.cc.
References numBJet, and Cuts::SetVars().
Referenced by KinematicsSelector().
double specialAna::calc_lep_fraction ()
Definition at line 1752 of file specialAna.cc.
References JetList, sel_lepton_nprompt, and sel_lepton_prompt.
Referenced by Leptonic_fraction_cut().
void specialAna::channel_writer (TFile * file, const char * channel)
Definition at line 2040 of file specialAna.cc.
References channel_stages, and file1.
Referenced by endJob().
bool specialAna::Check_Ele_ID (pxl::Particle * ele, bool do_pt_cut = true, bool do_eta_cut = true)
Definition at line 1607 of file specialAna.cc.
Referenced by Check_Par_ID().
bool specialAna::Check_Muo_ID (pxl::Particle * muon, bool do_pt_cut = true, bool do_eta_cut = true)
Definition at line 1587 of file specialAna.cc.
References b_13TeV, and b_8TeV.
Referenced by analyseEvent(), and Check_Par_ID().
bool specialAna::Check_Par_ID (pxl::Particle * part, bool do_pt_cut = true, bool do_eta_cut = true)
Definition at line 1553 of file specialAna.cc.
References Check_Ele_ID(), Check_Muo_ID(), Check_Tau_ID(), and m_TauType.
Referenced by FindResonance(), Get_Trigger_match_1(), and Get_Trigger_match_2().
bool specialAna::Check_Tau_ID (pxl::Particle * tau)
Definition at line 1569 of file specialAna.cc.
References b_13TeV, and b_8TeV.
Referenced by analyseEvent(), and Check_Par_ID().
void specialAna::Create_Gen_histograms (const char * channel, const char * part1, const char * part2)
Resonant mass histogram
First particle histograms
Second particle histograms
Delta phi between the two particles
pT ratio of the two particles
Definition at line 1289 of file specialAna.cc.
void specialAna::Create_N1_histos (const char * channel, const std::map< std::string, Cuts > & m_cfg, std::string const endung = "")
Definition at line 1209 of file specialAna.cc.
void specialAna::Create_RECO_effs ()
Definition at line 949 of file specialAna.cc.
References Create_RECO_object_effs().
void specialAna::Create_RECO_object_effs (std::string object)
Definition at line 956 of file specialAna.cc.
Referenced by Create_RECO_effs().
void specialAna::Create_Resonance_histograms (int n_histos, const char * channel, const char * part1, const char * part2, std::string const endung = "")
Cutflow histogram
Resonant mass histogram
Resonant mass resolution histogram
First particle histograms
Second particle histograms
Delta phi between the two particles
pT ratio of the two particles
Create histograms for channels with MET
MET histograms
Corrected second particle histogram
Delta phi between the other particles
pT ratio of the other particles
Definition at line 1323 of file specialAna.cc.
void specialAna::Create_trigger_effs ()
Definition at line 1023 of file specialAna.cc.
References m_trigger_string, and trigger_defs.
double specialAna::DeltaPhi (double a, double b)
Definition at line 1949 of file specialAna.cc.
Referenced by DeltaR(), Fill_Gen_histograms(), Fill_RECO_object_effs(), Fill_Resonance_histograms(), Make_DeltaPhi_emu(), Make_DeltaPhi_mutau(), Make_DeltaPhi_tauemu(), and Make_DeltaPhi_tauMET().
double specialAna::DeltaPhi (pxl::Particle * lepton, pxl::Particle * met)
Definition at line 1958 of file specialAna.cc.
double specialAna::DeltaR (pxl::Particle * lepton, pxl::Particle * met)
Definition at line 1969 of file specialAna.cc.
References DeltaPhi().
Referenced by Fill_RECO_object_effs(), and Get_Trigger_match_1().
void specialAna::endEvent (const pxl::Event * event)
Definition at line 2284 of file specialAna.cc.
References EleList, EleListGen, GammaList, GammaListGen, JetList, JetListGen, keep_data_event, METList, METListGen, MuonList, MuonListGen, runOnData, TauList, and TauListGen.
Referenced by analyseEvent().
void specialAna::endJob (const Serializable *) virtual
Definition at line 2074 of file specialAna.cc.
References channel_writer(), doTriggerStudies, file1, runOnData, and triggers.
void specialAna::Fill_Gen_Controll_histo ()
Definition at line 1837 of file specialAna.cc.
References m_GenEvtView, and S3ListGen.
Referenced by analyseEvent().
void specialAna::Fill_Gen_histograms (const char * channel, const char * part1, const char * part2)
Resonant mass histogram
First particle histograms
Second particle histograms
Delta phi between the two particles
pT ratio of the two particles
Definition at line 1306 of file specialAna.cc.
References DeltaPhi(), resonance_mass_gen, sel_part1_gen, sel_part2_gen, and weight.
Referenced by GenSelector().
void specialAna::Fill_Gen_histograms (int n_histos, const char * channel, const char * part1, const char * part2)
void specialAna::Fill_N1_histos (const char * channel, const std::map< std::string, Cuts > & m_cfg, std::string const endung = "")
Definition at line 1223 of file specialAna.cc.
References weight.
Referenced by KinematicsSelector().
void specialAna::Fill_Particle_histos (int hist_number, pxl::Particle * lepton)
Definition at line 1873 of file specialAna.cc.
References Get_Truth_match(), m_METType, m_TauType, and weight.
Referenced by analyseEvent().
void specialAna::Fill_RECO_effs ()
Definition at line 965 of file specialAna.cc.
References EleList, Fill_RECO_object_effs(), METList, MuonList, and TauList.
Referenced by analyseEvent().
void specialAna::Fill_RECO_object_effs (std::string object, int id, std::vector< pxl::Particle * > part_list)
Definition at line 972 of file specialAna.cc.
References DeltaPhi(), DeltaR(), m_RecEvtView, and S3ListGen.
Referenced by Fill_RECO_effs().
void specialAna::Fill_Resonance_histograms (int n_histos, const char * channel, const char * part1, const char * part2, std::string const endung = "")
Cutflow histogram
Resonant mass histogram
Resonant mass resolution histogram
First particle histograms
Second particle histograms
Delta phi between the two particles
pT ratio of the two particles
Create histograms for channels with MET
MET histograms
Corrected second particle histogram
Delta phi between the other particles
pT ratio of the other particles
Definition at line 1365 of file specialAna.cc.
References DeltaPhi(), resonance_mass, resonance_mass_gen, sel_lepton_nprompt, sel_lepton_nprompt_corr, sel_lepton_prompt, sel_met, and weight.
Referenced by KinematicsSelector().
void specialAna::Fill_trigger_effs ()
Definition at line 1053 of file specialAna.cc.
References Get_Trigger_match_1(), Get_Trigger_match_2(), m_trigger_string, and trigger_defs.
Referenced by analyseEvent().
void specialAna::FillControllHistos ()
Definition at line 604 of file specialAna.cc.
References event_weight, getHT(), getPtHat(), m_RecEvtView, pileup_weight, runOnData, and weight.
Referenced by analyseEvent().
void specialAna::FillSystematics (const pxl::Event * event, std::string const particleName)
Definition at line 507 of file specialAna.cc.
References FillSystematicsUpDown().
Referenced by analyseEvent().
void specialAna::FillSystematicsUpDown (const pxl::Event * event, std::string const particleName, std::string const updown, std::string const shiftType)
extract one EventView make sure the object key is the same as in Systematics.cc specified
get all particles
backup OldList
reset the chosen MET and lepton
return to backup
Definition at line 514 of file specialAna.cc.
References EleList, KinematicsSelector(), m_METType, m_TauType, METList, MuonList, RememberMET, RememberPart, resonance_mass, resonance_mass_gen, sel_lepton_nprompt, sel_lepton_nprompt_corr, sel_lepton_prompt, sel_met, and TauList.
Referenced by analyseEvent(), and FillSystematics().
bool specialAna::FindResonance (const char * channel, std::vector< pxl::Particle * > gen_list)
Definition at line 1408 of file specialAna.cc.
References b_13TeV, b_8TeV, resonance_mass_gen, sel_part1_gen, and sel_part2_gen.
Referenced by GenSelector(), and KinematicsSelector().
bool specialAna::FindResonance (const char * channel, std::vector< pxl::Particle * > part1_list, std::vector< pxl::Particle * > part2_list)
Definition at line 1466 of file specialAna.cc.
References Check_Par_ID(), resonance_mass, sel_lepton_nprompt, and sel_lepton_prompt.
bool specialAna::FindResonance (const char * channel, std::vector< pxl::Particle * > part1_list, std::vector< pxl::Particle * > part2_list, std::vector< pxl::Particle * > met_list)
use tau eta to project MET
rotate MET to tau direction
project MET to tau direction
project MET parallel to tau direction
Definition at line 1491 of file specialAna.cc.
References Check_Par_ID(), resonance_mass, sel_lepton_nprompt, sel_lepton_nprompt_corr, sel_lepton_prompt, and sel_met.
void specialAna::GenSelector ()
Definition at line 1251 of file specialAna.cc.
References b_emu, b_etau, b_etaue, b_etaumu, b_mutau, b_mutaue, b_mutaumu, Fill_Gen_histograms(), FindResonance(), and S3ListGen.
Referenced by analyseEvent().
void specialAna::Get_Trigger_match_1 (std::string trigger_name)
Definition at line 1146 of file specialAna.cc.
References Check_Par_ID(), DeltaR(), EleList, m_RecEvtView, m_TrigEvtView, MuonList, particles, TauList, and trigger_defs.
Referenced by Fill_trigger_effs().
void specialAna::Get_Trigger_match_2 (std::string trigger_name)
Definition at line 1063 of file specialAna.cc.
References Check_Par_ID(), EleList, m_RecEvtView, m_TrigEvtView, MuonList, TauList, and trigger_defs.
Referenced by Fill_trigger_effs().
pxl::Particle * specialAna::Get_Truth_match (std::string name, pxl::Particle * lepton)
Definition at line 1916 of file specialAna.cc.
References b_13TeV, b_8TeV, and S3ListGen.
Referenced by Fill_Particle_histos().
double specialAna::getHT ()
Definition at line 2029 of file specialAna.cc.
References BJetList, and JetList.
Referenced by FillControllHistos().
double specialAna::getPtHat ()
Definition at line 1980 of file specialAna.cc.
References b_13TeV, b_8TeV, and S3ListGen.
Referenced by FillControllHistos().
void specialAna::Init_emu_cuts ()
Definition at line 614 of file specialAna.cc.
References emu_cut_cfgs.
void specialAna::Init_etau_cuts ()
Definition at line 621 of file specialAna.cc.
References etau_cut_cfgs.
void specialAna::Init_etaue_cuts ()
Definition at line 635 of file specialAna.cc.
References etaue_cut_cfgs.
void specialAna::Init_etaumu_cuts ()
Definition at line 639 of file specialAna.cc.
References etaumu_cut_cfgs.
void specialAna::Init_mutau_cuts ()
Definition at line 625 of file specialAna.cc.
References mutau_cut_cfgs.
void specialAna::Init_mutaue_cuts ()
Definition at line 643 of file specialAna.cc.
References mutaue_cut_cfgs.
void specialAna::Init_mutaumu_cuts ()
Definition at line 652 of file specialAna.cc.
References mutaumu_cut_cfgs.
void specialAna::initEvent (const pxl::Event * event)
Definition at line 2132 of file specialAna.cc.
References b_13TeV, b_8TeV, BJetList, EleList, EleListGen, event_weight, events_, GammaList, GammaListGen, JetList, JetListGen, keep_data_event, m_BJets_algo, m_dataPeriod, m_GenEvtView, m_JetAlgo, m_METType, m_RecEvtView, m_TauType, m_TrigEvtView, METList, METListGen, mkeep_resonance_mass, MuonList, MuonListGen, numBJet, numEle, numGamma, numJet, numMET, numMuon, numTau, pileup_weight, resonance_mass, resonance_mass_gen, runOnData, S3ListGen, sel_lepton_nprompt, sel_lepton_nprompt_corr, sel_lepton_prompt, sel_met, TauList, TauListGen, temp_event, temp_ls, temp_run, and weight.
Referenced by analyseEvent().
void specialAna::KinematicsSelector (std::string const endung = "")
Selection for the e-mu channel
Make the same-sign charge cut
Make the b-jet veto
Make the cut on DeltaPhi(e,mu)
Selection for the e-tau_h channel
Selection for the muo-tau_h channel
Find the actual resonance
Make the cut on zeta
Make the cut on DeltaPhi(tau,MET)
Make the cut on DeltaPhi(mu,tau)
Make the b-jet veto
Make the same-sign charge cut
Make the M_T cut
Fill the N-1 histograms
Selection for the e-tau_e channel
Selection for the e-tau_muo channel
Selection for the muo-tau_e channel
Find the actual resonance
Make the b-jet veto
Make the cut on DeltaPhi(e,mu)
Make the cut on the leptonic pT fraction
Make the cut on the pT ratio of mu and tau
Make the cut on the pT ratio of mu and ele
Selection for the muo-tau_muo channel
Definition at line 656 of file specialAna.cc.
References b_emu, b_etau, b_etaue, b_etaumu, b_mutau, b_mutaue, b_mutaumu, Bjet_veto(), EleList, emu_cut_cfgs, etau_cut_cfgs, etaue_cut_cfgs, etaumu_cut_cfgs, event_weight, Fill_N1_histos(), Fill_Resonance_histograms(), FindResonance(), keep_data_event, Leptonic_fraction_cut(), m_RecEvtView, Make_DeltaPhi_emu(), Make_DeltaPhi_mutau(), Make_DeltaPhi_tauemu(), Make_DeltaPhi_tauMET(), Make_zeta_cut(), METList, mkeep_resonance_mass, MT_cut(), MuonList, mutau_cut_cfgs, mutaue_cut_cfgs, mutaumu_cut_cfgs, OppSign_charge(), pileup_weight, pT_muele_ratio_cut(), pT_mutau_ratio_cut(), resonance_mass, and TauList.
Referenced by analyseEvent(), and FillSystematicsUpDown().
bool specialAna::Leptonic_fraction_cut (Cuts * cuts)
Definition at line 1763 of file specialAna.cc.
References calc_lep_fraction(), sel_lepton_nprompt, sel_lepton_prompt, and Cuts::SetVars().
Referenced by KinematicsSelector().
bool specialAna::Make_DeltaPhi_emu (Cuts * cuts)
Definition at line 1702 of file specialAna.cc.
References DeltaPhi(), sel_lepton_nprompt, sel_lepton_prompt, and Cuts::SetVars().
Referenced by KinematicsSelector().
bool specialAna::Make_DeltaPhi_mutau (Cuts * cuts)
Definition at line 1674 of file specialAna.cc.
References DeltaPhi(), sel_lepton_nprompt, sel_lepton_prompt, and Cuts::SetVars().
Referenced by KinematicsSelector().
bool specialAna::Make_DeltaPhi_tauemu (Cuts * cuts)
Definition at line 1688 of file specialAna.cc.
References DeltaPhi(), sel_lepton_nprompt, sel_lepton_prompt, and Cuts::SetVars().
Referenced by KinematicsSelector().
bool specialAna::Make_DeltaPhi_tauMET (Cuts * cuts)
Definition at line 1660 of file specialAna.cc.
References DeltaPhi(), sel_lepton_nprompt, sel_met, and Cuts::SetVars().
Referenced by KinematicsSelector().
bool specialAna::Make_zeta_cut (Cuts * cuts)
Definition at line 1648 of file specialAna.cc.
References Make_zeta_stuff(), sel_lepton_nprompt, sel_lepton_prompt, sel_met, and Cuts::SetVars().
Referenced by KinematicsSelector().
std::vector< double > specialAna::Make_zeta_stuff (pxl::Particle * muon, pxl::Particle * tau, pxl::Particle * met)
Definition at line 1621 of file specialAna.cc.
Referenced by Make_zeta_cut().
double specialAna::MT (pxl::Particle * lepton, pxl::Particle * met)
Definition at line 1975 of file specialAna.cc.
Referenced by MT_cut().
bool specialAna::MT_cut (Cuts * cuts)
Definition at line 1738 of file specialAna.cc.
References MT(), sel_lepton_prompt, sel_met, and Cuts::SetVars().
Referenced by KinematicsSelector().
bool specialAna::OppSign_charge (Cuts * cuts)
Definition at line 1725 of file specialAna.cc.
References sel_lepton_nprompt, sel_lepton_prompt, and Cuts::SetVars().
Referenced by KinematicsSelector().
bool specialAna::pT_muele_ratio_cut (Cuts * cuts)
Definition at line 1792 of file specialAna.cc.
References sel_lepton_nprompt, sel_lepton_prompt, and Cuts::SetVars().
Referenced by KinematicsSelector().
bool specialAna::pT_mutau_ratio_cut (Cuts * cuts)
Definition at line 1777 of file specialAna.cc.
References sel_lepton_nprompt_corr, sel_lepton_prompt, and Cuts::SetVars().
Referenced by KinematicsSelector().
bool specialAna::tail_selector (const pxl::Event * event)
Diboson tail fitting
ttbar 8TeV tail fitting
ttbar 13TeV tail fitting
Signal parameter selection
Definition at line 392 of file specialAna.cc.
References b_13TeV, b_8TeV, config_, m_GenEvtView, S3ListGen, and weight.
Referenced by analyseEvent().
bool specialAna::TriggerSelector (const pxl::Event * event)
Definition at line 1806 of file specialAna.cc.
References b_13TeV, b_8TeV, m_TrigEvtView, m_trigger_string, and triggers.
Referenced by analyseEvent().
Member Data Documentation
bool specialAna::b_13TeV
Definition at line 178 of file specialAna.hh.
Referenced by Check_Muo_ID(), Check_Tau_ID(), FindResonance(), Get_Truth_match(), getPtHat(), initEvent(), tail_selector(), and TriggerSelector().
bool specialAna::b_14TeV
Definition at line 177 of file specialAna.hh.
bool specialAna::b_8TeV
Definition at line 179 of file specialAna.hh.
Referenced by Check_Muo_ID(), Check_Tau_ID(), FindResonance(), Get_Truth_match(), getPtHat(), initEvent(), tail_selector(), and TriggerSelector().
bool specialAna::b_emu
Definition at line 181 of file specialAna.hh.
Referenced by GenSelector(), and KinematicsSelector().
bool specialAna::b_etau
Definition at line 182 of file specialAna.hh.
Referenced by GenSelector(), and KinematicsSelector().
bool specialAna::b_etaue
Definition at line 184 of file specialAna.hh.
Referenced by GenSelector(), and KinematicsSelector().
bool specialAna::b_etaumu
Definition at line 185 of file specialAna.hh.
Referenced by GenSelector(), and KinematicsSelector().
bool specialAna::b_mutau
Definition at line 183 of file specialAna.hh.
Referenced by GenSelector(), and KinematicsSelector().
bool specialAna::b_mutaue
Definition at line 186 of file specialAna.hh.
Referenced by GenSelector(), and KinematicsSelector().
bool specialAna::b_mutaumu
Definition at line 187 of file specialAna.hh.
Referenced by GenSelector(), and KinematicsSelector().
std::vector< pxl::Particle* >* specialAna::BJetList
Definition at line 164 of file specialAna.hh.
Referenced by getHT(), and initEvent().
std::map< std::string, int > specialAna::channel_stages
Definition at line 199 of file specialAna.hh.
Referenced by channel_writer().
const Tools::MConfig specialAna::config_
Definition at line 139 of file specialAna.hh.
Referenced by tail_selector().
TString specialAna::d_mydisc[66]
Definition at line 130 of file specialAna.hh.
TString specialAna::d_mydiscmu[6]
Definition at line 136 of file specialAna.hh.
bool specialAna::doTriggerStudies
Definition at line 124 of file specialAna.hh.
Referenced by analyseEvent(), and endJob().
std::vector< pxl::Particle* >* specialAna::EleList
Definition at line 158 of file specialAna.hh.
Referenced by analyseEvent(), endEvent(), Fill_RECO_effs(), FillSystematicsUpDown(), Get_Trigger_match_1(), Get_Trigger_match_2(), initEvent(), and KinematicsSelector().
std::vector< pxl::Particle* >* specialAna::EleListGen
Definition at line 169 of file specialAna.hh.
Referenced by endEvent(), and initEvent().
std::map< std::string, Cuts > specialAna::emu_cut_cfgs
Definition at line 189 of file specialAna.hh.
Referenced by Init_emu_cuts(), and KinematicsSelector().
std::map< std::string, Cuts > specialAna::etau_cut_cfgs
Definition at line 190 of file specialAna.hh.
Referenced by Init_etau_cuts(), and KinematicsSelector().
std::map< std::string, Cuts > specialAna::etaue_cut_cfgs
Definition at line 192 of file specialAna.hh.
Referenced by Init_etaue_cuts(), and KinematicsSelector().
std::map< std::string, Cuts > specialAna::etaumu_cut_cfgs
Definition at line 193 of file specialAna.hh.
Referenced by Init_etaumu_cuts(), and KinematicsSelector().
double specialAna::event_weight
Definition at line 219 of file specialAna.hh.
Referenced by FillControllHistos(), initEvent(), and KinematicsSelector().
int specialAna::events_
Definition at line 155 of file specialAna.hh.
Referenced by initEvent().
TFile* specialAna::file1
Definition at line 38 of file specialAna.hh.
Referenced by channel_writer(), and endJob().
std::vector< pxl::Particle* >* specialAna::GammaList
Definition at line 161 of file specialAna.hh.
Referenced by endEvent(), and initEvent().
std::vector< pxl::Particle* >* specialAna::GammaListGen
Definition at line 172 of file specialAna.hh.
Referenced by endEvent(), and initEvent().
bool specialAna::isOldPXLFile
Definition at line 132 of file specialAna.hh.
std::vector< pxl::Particle* >* specialAna::JetList
Definition at line 163 of file specialAna.hh.
Referenced by calc_lep_fraction(), endEvent(), getHT(), and initEvent().
std::vector< pxl::Particle* >* specialAna::JetListGen
Definition at line 174 of file specialAna.hh.
Referenced by endEvent(), and initEvent().
bool specialAna::keep_data_event
Definition at line 216 of file specialAna.hh.
Referenced by endEvent(), initEvent(), and KinematicsSelector().
const std::string specialAna::m_BJets_algo
Definition at line 125 of file specialAna.hh.
Referenced by initEvent().
const std::string specialAna::m_channel
Definition at line 138 of file specialAna.hh.
const std::string specialAna::m_cutdatafile
Definition at line 134 of file specialAna.hh.
const std::string specialAna::m_dataPeriod
Definition at line 137 of file specialAna.hh.
Referenced by initEvent().
pxl::EventView* specialAna::m_GenEvtView
Definition at line 120 of file specialAna.hh.
Referenced by Fill_Gen_Controll_histo(), initEvent(), and tail_selector().
const std::string specialAna::m_JetAlgo
Definition at line 125 of file specialAna.hh.
Referenced by initEvent().
const std::string specialAna::m_METType
Definition at line 125 of file specialAna.hh.
Referenced by Fill_Particle_histos(), FillSystematicsUpDown(), and initEvent().
pxl::EventView* specialAna::m_RecEvtView
Definition at line 119 of file specialAna.hh.
Referenced by Fill_RECO_object_effs(), FillControllHistos(), Get_Trigger_match_1(), Get_Trigger_match_2(), initEvent(), and KinematicsSelector().
const std::string specialAna::m_TauType
Definition at line 125 of file specialAna.hh.
Referenced by Check_Par_ID(), Fill_Particle_histos(), FillSystematicsUpDown(), and initEvent().
pxl::EventView* specialAna::m_TrigEvtView
Definition at line 121 of file specialAna.hh.
Referenced by Get_Trigger_match_1(), Get_Trigger_match_2(), initEvent(), and TriggerSelector().
const std::vector< std::string > specialAna::m_trigger_string
Definition at line 135 of file specialAna.hh.
Referenced by Create_trigger_effs(), Fill_trigger_effs(), and TriggerSelector().
std::vector< pxl::Particle* >* specialAna::METList
Definition at line 162 of file specialAna.hh.
Referenced by analyseEvent(), endEvent(), Fill_RECO_effs(), FillSystematicsUpDown(), initEvent(), and KinematicsSelector().
std::vector< pxl::Particle* >* specialAna::METListGen
Definition at line 173 of file specialAna.hh.
Referenced by endEvent(), and initEvent().
std::map< std::string, float > specialAna::mkeep_resonance_mass
Definition at line 217 of file specialAna.hh.
Referenced by initEvent(), and KinematicsSelector().
std::map< std::string, float > specialAna::mLeptonTree
Definition at line 214 of file specialAna.hh.
std::vector< pxl::Particle* >* specialAna::MuonList
Definition at line 159 of file specialAna.hh.
Referenced by analyseEvent(), endEvent(), Fill_RECO_effs(), FillSystematicsUpDown(), Get_Trigger_match_1(), Get_Trigger_match_2(), initEvent(), and KinematicsSelector().
std::vector< pxl::Particle* >* specialAna::MuonListGen
Definition at line 170 of file specialAna.hh.
Referenced by endEvent(), and initEvent().
std::map< std::string, Cuts > specialAna::mutau_cut_cfgs
Definition at line 191 of file specialAna.hh.
Referenced by Init_mutau_cuts(), and KinematicsSelector().
std::map< std::string, Cuts > specialAna::mutaue_cut_cfgs
Definition at line 194 of file specialAna.hh.
Referenced by Init_mutaue_cuts(), and KinematicsSelector().
std::map< std::string, Cuts > specialAna::mutaumu_cut_cfgs
Definition at line 195 of file specialAna.hh.
Referenced by Init_mutaumu_cuts(), and KinematicsSelector().
unsigned int specialAna::n_lepton
Definition at line 156 of file specialAna.hh.
unsigned int specialAna::numBJet
Definition at line 153 of file specialAna.hh.
Referenced by Bjet_veto(), and initEvent().
unsigned int specialAna::numEle
Definition at line 148 of file specialAna.hh.
Referenced by initEvent().
unsigned int specialAna::numGamma
Definition at line 150 of file specialAna.hh.
Referenced by initEvent().
unsigned int specialAna::numJet
Definition at line 152 of file specialAna.hh.
Referenced by initEvent().
unsigned int specialAna::numMET
Definition at line 151 of file specialAna.hh.
Referenced by initEvent().
unsigned int specialAna::numMuon
Definition at line 147 of file specialAna.hh.
Referenced by initEvent().
unsigned int specialAna::numTau
Definition at line 149 of file specialAna.hh.
Referenced by initEvent().
const std::string specialAna::particles[4] = {"Ele", "Muon", "Tau", "MET"}
Definition at line 127 of file specialAna.hh.
Referenced by Get_Trigger_match_1().
const std::string specialAna::particleSymbols[4] = {"e", "#mu", "#tau", "E_{T}^{miss}"}
Definition at line 128 of file specialAna.hh.
double specialAna::pileup_weight
Definition at line 220 of file specialAna.hh.
Referenced by FillControllHistos(), initEvent(), and KinematicsSelector().
std::vector< pxl::Particle* >* specialAna::RememberMET
Definition at line 167 of file specialAna.hh.
Referenced by FillSystematicsUpDown().
std::vector< pxl::Particle* >* specialAna::RememberPart
Definition at line 166 of file specialAna.hh.
Referenced by FillSystematicsUpDown().
std::map< std::string, double > specialAna::resonance_mass
Definition at line 209 of file specialAna.hh.
Referenced by Fill_Resonance_histograms(), FillSystematicsUpDown(), FindResonance(), initEvent(), and KinematicsSelector().
std::map< std::string, double > specialAna::resonance_mass_gen
Definition at line 210 of file specialAna.hh.
Referenced by Fill_Gen_histograms(), Fill_Resonance_histograms(), FillSystematicsUpDown(), FindResonance(), and initEvent().
bool specialAna::runOnData
Definition at line 123 of file specialAna.hh.
Referenced by analyseEvent(), endEvent(), endJob(), FillControllHistos(), and initEvent().
std::vector< pxl::Particle* >* specialAna::S3ListGen
Definition at line 175 of file specialAna.hh.
Referenced by Fill_Gen_Controll_histo(), Fill_RECO_object_effs(), GenSelector(), Get_Truth_match(), getPtHat(), initEvent(), and tail_selector().
pxl::Particle* specialAna::sel_lepton_nprompt
Definition at line 205 of file specialAna.hh.
Referenced by calc_lep_fraction(), Fill_Resonance_histograms(), FillSystematicsUpDown(), FindResonance(), initEvent(), Leptonic_fraction_cut(), Make_DeltaPhi_emu(), Make_DeltaPhi_mutau(), Make_DeltaPhi_tauemu(), Make_DeltaPhi_tauMET(), Make_zeta_cut(), OppSign_charge(), and pT_muele_ratio_cut().
pxl::Particle* specialAna::sel_lepton_nprompt_corr
Definition at line 207 of file specialAna.hh.
Referenced by Fill_Resonance_histograms(), FillSystematicsUpDown(), FindResonance(), initEvent(), and pT_mutau_ratio_cut().
pxl::Particle* specialAna::sel_lepton_prompt
Definition at line 204 of file specialAna.hh.
Referenced by calc_lep_fraction(), Fill_Resonance_histograms(), FillSystematicsUpDown(), FindResonance(), initEvent(), Leptonic_fraction_cut(), Make_DeltaPhi_emu(), Make_DeltaPhi_mutau(), Make_DeltaPhi_tauemu(), Make_zeta_cut(), MT_cut(), OppSign_charge(), pT_muele_ratio_cut(), and pT_mutau_ratio_cut().
pxl::Particle* specialAna::sel_met
Definition at line 206 of file specialAna.hh.
Referenced by Fill_Resonance_histograms(), FillSystematicsUpDown(), FindResonance(), initEvent(), Make_DeltaPhi_tauMET(), Make_zeta_cut(), and MT_cut().
pxl::Particle* specialAna::sel_part1_gen
Definition at line 201 of file specialAna.hh.
Referenced by Fill_Gen_histograms(), and FindResonance().
pxl::Particle* specialAna::sel_part2_gen
Definition at line 202 of file specialAna.hh.
Referenced by Fill_Gen_histograms(), and FindResonance().
std::vector< pxl::Particle* >* specialAna::TauList
Definition at line 160 of file specialAna.hh.
Referenced by analyseEvent(), endEvent(), Fill_RECO_effs(), FillSystematicsUpDown(), Get_Trigger_match_1(), Get_Trigger_match_2(), initEvent(), and KinematicsSelector().
std::vector< pxl::Particle* >* specialAna::TauListGen
Definition at line 171 of file specialAna.hh.
Referenced by endEvent(), and initEvent().
double specialAna::temp_event
Definition at line 143 of file specialAna.hh.
Referenced by initEvent().
double specialAna::temp_ls
Definition at line 142 of file specialAna.hh.
Referenced by initEvent().
double specialAna::temp_run
Definition at line 141 of file specialAna.hh.
Referenced by initEvent().
std::map< std::string, Trigger * > specialAna::trigger_defs
Definition at line 197 of file specialAna.hh.
Referenced by Create_trigger_effs(), Fill_trigger_effs(), Get_Trigger_match_1(), and Get_Trigger_match_2().
std::unordered_set< std::string > specialAna::triggers
Definition at line 212 of file specialAna.hh.
Referenced by endJob(), and TriggerSelector().
double specialAna::weight
Definition at line 145 of file specialAna.hh.
Referenced by analyseEvent(), Fill_Gen_histograms(), Fill_N1_histos(), Fill_Particle_histos(), Fill_Resonance_histograms(), FillControllHistos(), initEvent(), and tail_selector().
The documentation for this class was generated from the following files:
specialAna.hh
specialAna.cc