.TH "specialAna.cc" 3 "Wed Mar 18 2015" "RPV-LFV-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
specialAna.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'specialAna\&.hh'\fP
.br
\fC#include 'HistClass\&.hh'\fP
.br
\fC#include 'Tools/Tools\&.hh'\fP
.br
\fC#include 'boost/format\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBm_dataPeriod\fP (cfg\&.GetItem< std::string >('General\&.DataPeriod'))"
.br
.ti -1c
.RI "\fBm_channel\fP (cfg\&.GetItem< std::string >('RPV\&.channel'))"
.br
.ti -1c
.RI "\fBconfig_\fP (cfg)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "config_ (cfg)"

.PP
 Init for the e-mu channel 
.PP
 Init for the e-tau_h channel 
.PP
 Init for the mu-tau_h channel 
.PP
 Init for the e-tau_e channel 
.PP
 Init for the e-tau_mu channel 
.PP
 Init for the mu-tau_e channel 
.PP
 Init for the mu-tau_mu channel 
.PP
Definition at line 22 of file specialAna\&.cc\&.
.PP
References m_channel(), and m_dataPeriod()\&.
.SS "m_channel (cfg\&.GetItem< std::string >'RPV\&.channel')"

.PP
Referenced by config_()\&.
.SS "m_dataPeriod (cfg\&.GetItem< std::string >'General\&.DataPeriod')"

.PP
Referenced by config_()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RPV-LFV-Analyzer from the source code\&.
