.TH "Trigger" 3 "Wed Mar 18 2015" "RPV-LFV-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trigger \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TriggerClass\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrigger\fP (std::string input_trigger_name)"
.br
.ti -1c
.RI "void \fBDoAcceptCuts\fP (bool accep_cuts=true)"
.br
.ti -1c
.RI "bool \fBGetDimension\fP () const "
.br
.ti -1c
.RI "bool \fBGetAcceptCuts\fP () const "
.br
.ti -1c
.RI "std::string \fBGetPart1Name\fP () const "
.br
.ti -1c
.RI "std::string \fBGetPart2Name\fP () const "
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBsplit\fP (const std::string &s, char delim, std::vector< std::string > *elems)"
.br
.ti -1c
.RI "std::vector< std::string > \fBsplit\fP (const std::string &s, char delim)"
.br
.ti -1c
.RI "std::vector< std::string > \fBGet_trigger_seeds\fP (const std::string input_trigger_name)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBtrigger_name\fP"
.br
.ti -1c
.RI "std::string \fBpart_1_name\fP"
.br
.ti -1c
.RI "std::string \fBpart_2_name\fP"
.br
.ti -1c
.RI "bool \fBtwo_dimensions\fP"
.br
.ti -1c
.RI "bool \fBdo_accept_cuts\fP"
.br
.ti -1c
.RI "std::vector< pxl::Particle * > * \fBparticles_1\fP"
.br
.ti -1c
.RI "std::vector< pxl::Particle * > * \fBparticles_2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file TriggerClass\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Trigger::Trigger (std::stringinput_trigger_name)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 9 of file TriggerClass\&.hh\&.
.PP
References Get_trigger_seeds(), part_1_name, part_2_name, trigger_name, and two_dimensions\&.
.SH "Member Function Documentation"
.PP 
.SS "void Trigger::DoAcceptCuts (boolaccep_cuts = \fCtrue\fP)\fC [inline]\fP"

.PP
Definition at line 17 of file TriggerClass\&.hh\&.
.PP
References do_accept_cuts\&.
.SS "std::vector< std::string > Trigger::Get_trigger_seeds (const std::stringinput_trigger_name)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 52 of file TriggerClass\&.hh\&.
.PP
References part_1_name, part_2_name, split(), and two_dimensions\&.
.PP
Referenced by Trigger()\&.
.SS "bool Trigger::GetAcceptCuts () const\fC [inline]\fP"

.PP
Definition at line 25 of file TriggerClass\&.hh\&.
.PP
References do_accept_cuts\&.
.SS "bool Trigger::GetDimension () const\fC [inline]\fP"

.PP
Definition at line 21 of file TriggerClass\&.hh\&.
.PP
References two_dimensions\&.
.SS "std::string Trigger::GetPart1Name () const\fC [inline]\fP"

.PP
Definition at line 29 of file TriggerClass\&.hh\&.
.PP
References part_1_name\&.
.SS "std::string Trigger::GetPart2Name () const\fC [inline]\fP"

.PP
Definition at line 33 of file TriggerClass\&.hh\&.
.PP
References part_2_name\&.
.SS "void Trigger::split (const std::string &s, chardelim, std::vector< std::string > *elems)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 38 of file TriggerClass\&.hh\&.
.PP
Referenced by Get_trigger_seeds(), and split()\&.
.SS "std::vector<std::string> Trigger::split (const std::string &s, chardelim)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 46 of file TriggerClass\&.hh\&.
.PP
References split()\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Trigger::do_accept_cuts\fC [private]\fP"

.PP
Definition at line 97 of file TriggerClass\&.hh\&.
.PP
Referenced by DoAcceptCuts(), and GetAcceptCuts()\&.
.SS "std::string Trigger::part_1_name\fC [private]\fP"

.PP
Definition at line 94 of file TriggerClass\&.hh\&.
.PP
Referenced by Get_trigger_seeds(), GetPart1Name(), and Trigger()\&.
.SS "std::string Trigger::part_2_name\fC [private]\fP"

.PP
Definition at line 95 of file TriggerClass\&.hh\&.
.PP
Referenced by Get_trigger_seeds(), GetPart2Name(), and Trigger()\&.
.SS "std::vector< pxl::Particle* >* Trigger::particles_1\fC [private]\fP"

.PP
Definition at line 98 of file TriggerClass\&.hh\&.
.SS "std::vector< pxl::Particle* >* Trigger::particles_2\fC [private]\fP"

.PP
Definition at line 99 of file TriggerClass\&.hh\&.
.SS "std::string Trigger::trigger_name\fC [private]\fP"

.PP
Definition at line 93 of file TriggerClass\&.hh\&.
.PP
Referenced by Trigger()\&.
.SS "bool Trigger::two_dimensions\fC [private]\fP"

.PP
Definition at line 96 of file TriggerClass\&.hh\&.
.PP
Referenced by Get_trigger_seeds(), GetDimension(), and Trigger()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RPV-LFV-Analyzer from the source code\&.
